# generated by cabal-rpm-2.0.10
# https://docs.fedoraproject.org/en-US/packaging-guidelines/Haskell/

Name:           defloc
Version:        0.1.0.0
Release:        1%{?dist}
Summary:        Finds locations of function definitions in shell scripts

License:        GPLv3+
Url:            https://github.com/lzaoral/%{name}
Source0:        https://%{url}/archive/refs/tags/v%{version}/%{name}-%{version}.tar.gz

# Begin cabal-rpm deps:
BuildRequires:  ghc-Cabal-devel
BuildRequires:  ghc-rpm-macros
BuildRequires:  ghc-ShellCheck-static
BuildRequires:  ghc-base-static
BuildRequires:  ghc-containers-static
BuildRequires:  ghc-mtl-static
BuildRequires:  ghc-regex-pcre-static
# End cabal-rpm deps

%description
Simple tool based on ShellCheck's parser that can be used to find definitions
of functions in shell scripts.


%prep
# Begin cabal-rpm setup:
%setup -q
# End cabal-rpm setup


%build
# Begin cabal-rpm build:
%ghc_bin_build
# End cabal-rpm build


%install
# Begin cabal-rpm install
%ghc_bin_install
# End cabal-rpm install


%files
# Begin cabal-rpm files:
%license LICENSE
%doc CHANGELOG.md README.md
%{_bindir}/%{name}
# End cabal-rpm files


%changelog
* Tue Dec  7 2021 Lukáš Zaoral <lzaoral@redhat.com> - 0.1.0.0-1
- Initial release
